name: "Deploy develop"

on:
  workflow_run:
      workflows: ["Run tests"]
      branches: [ develop ]
      types:
        - completed

jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to develop server
        uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_STAGE}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
