name: "Deploy master"

on:
  workflow_run:
      workflows: ["Run tests"]
      branches: [ master ]
      types:
        - completed

jobs:
  deploy-master:
    runs-on: self-hosted
    strategy:
        matrix:
          node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production server
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
